### ISSUE TITLE
[BUG] Some templates do not not work correctly with quarkus.qute.strict-rendering=true

### ISSUE THREAD

**Issue by mkouba** [redhat-developer-demos/quarkus-petclinic#12]
See https://quarkus.io/guides/qute-reference#strict_rendering.

For example, [`{#if errors['firstName'] != null}`](https://github.com/redhat-developer-demos/quarkus-petclinic/blob/master/src/main/resources/templates/createOrUpdateOwnerForm.html#L7) results in a template exception if no error with the key `firstName` is present.

Solutions:
1. `{#if errors.containsKey('firstName')}` (preferred)
2. `{#if errors.['firstName'].or(false)}`
3. `quarkus.qute.strict-rendering=false` && `{#if errors['firstName']}`

**Comment by geoand** [comment]
Thanks, I'll have a look tomorrow
