### ISSUE TITLE
consider adding an open source license file to the project

### ISSUE THREAD

**Issue by aolle** [redhat-developer-demos/quarkus-petclinic#22]
Dear team,

 I would like to kindly request that you consider adding an open source license file to the project. It would greatly benefit the community to have clarity on the licensing terms and allow for more widespread use and contribution.

Thank you for your consideration.

Regards,

**Comment by geoand** [comment]
@lordofthejars mind taking care of this?

**Comment by lordofthejars** [comment]
Yes.

**Comment by geoand** [comment]
Thanks!
